version: "3"
services:
  app:
    build: ./
    command: streamlit run app.py --server.port 8501 --server.address=0.0.0.0
    volumes: 
      - ./:/app
    ports:
      - 8501:8501
    image: chatwithpdf:latest